name: "Terraform"

on:
  push:
    branches:
      - main
      - staging

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: |
          echo "::set-env name=TF_WORKSPACE::dev"
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "::set-env name=TF_WORKSPACE::prod"
