name: "Terraform Apply"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: false
        default: 'warning'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Check if Terrafrom Apply can be run on this commit-id
        if: !( startsWith(github.ref, 'dev/') || startsWith(github.ref, 'prod') )
        run: |
          echo "Cannot run Terraform Apply"
          exit 0
      - name: Set env to dev
        if: startsWith(github.ref, 'dev/')
        run: |
          echo "TF_WORKSPACE=dev" >> $GITHUB_ENV
      - name: Set env to prod
        if: startsWith(github.ref, 'prod')
        run: |
          echo "TF_WORKSPACE=prod" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve